### ISSUE TITLE
enhance UI / UX Design 

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#10]
- discuss about the design first

**Comment by HAXAZE** [comment]
1.Background should be Black
2.Playlist should be added like a. Recent playlist b. Hip Hop playlist c. Remix playlist d. Button color should be same  
I am a GSSOC'22 Contributor I would like to work on this issue.

**Comment by aarushimaurya** [comment]
Hello, I am a GSSoC participant, can you assign this to me?

**Comment by ZZENGAA** [comment]
hello, i also wanna contribute to this issue
