### ISSUE TITLE
Log in/ Sign up Page Interface

### ISSUE THREAD

**Issue by Yogeshlodhi** [flyingsonu122/tarana#109]
The email and password Boxes Should be aligned in the same line and should be put in a single large box to give it a clean UI  and the Sign up and Log in button should be of the complete width below password and email boxes.
The colors can be improved and also the hover effect on the Google account can be improved.

**Comment by Tushar98644** [comment]
I would like to solve this issue..

**Comment by Yogeshlodhi** [comment]
@Tushar98644 I'm already working on this issue
