### ISSUE TITLE
creating your own playlist by artist or genre

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#11]

**Comment by VartikaB** [comment]
Hello I am Vartika gssoc 2022 , I want to solve this issue.

**Comment by flyingsonu122** [comment]
Hi @VartikaB please solve it.

**Comment by VartikaB** [comment]
Thankyou sir I will work on it.

**Comment by Rishabh-Gaud** [comment]
good evening sir, I am Rishabh Kumar Gaud. I want to create playlists by genre and artist.  Give me chance to solve this issue

**Comment by VartikaB** [comment]
@Rishabh-Gaud can we work together? This will progress the task too in a better speed.

**Comment by Rishabh-Gaud** [comment]
> @Rishabh-Gaud can we work together? This will progress the task too in a better speed.

you can count on me

**Comment by lokita282** [comment]
I would like to work on this issue under GSSOC '22
