### ISSUE TITLE
fetch lyrics for songs to display

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#12]

**Comment by biswajit150803** [comment]
I want to work on this issue under GSSoc'22.

**Comment by akrati-max** [comment]
i am Akrati Gssoc 22 .i want to work on this issue

**Comment by biswajit150803** [comment]
> I want to work on this issue under GSSoc'22.

@flyingsonu122  You have given a like.So is this work assigned to me or not can you plz specify?

**Comment by Aditya3403** [comment]
I would like to work on this issue . Kindly assign this issue to me.

**Comment by prer45** [comment]
I would also like to work on this issue . Please assign it to me
