### ISSUE TITLE
For Codepeak-Spotify Branch- show recently played songs, recommendations 

### ISSUE THREAD

**Issue by Abhijeet-2003** [flyingsonu122/tarana#129]

**Comment by Abhijeet-2003** [comment]
Will start working on it as soon as you assign it to me @flyingsonu122 .

**Comment by flyingsonu122** [comment]
@Abhijeet-2003 assigned to you

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 Can I split this into 2 issues, this one will be to show recently played songs and recommendations. The other one will be to create a user page with followed artists, albums, playlists, and liked songs.

**Comment by flyingsonu122** [comment]
Go ahead @Abhijeet-2003

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 . I have sent a pr for this issue. Please review and merge.

**Comment by Abhijeet-2003** [comment]
What would be the points for pr #131? @flyingsonu122

**Comment by flyingsonu122** [comment]
Points given

**Comment by Abhijeet-2003** [comment]
Maybe there's some error, I haven't received any points. @flyingsonu122

**Comment by flyingsonu122** [comment]
@Abhijeet-2003 fixed level name issue , pls check your points now or after some time
