### ISSUE TITLE
add more songs 

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#13]
**We don't want to manually upload songs,**

Add functionality to the website to fetch songs from users device and other online sources or API

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by fleurdelis07** [comment]
Can I work on this issue for GSSOC'22

**Comment by flyingsonu122** [comment]
> Can I work on this issue for GSSOC'22

Yes, you should work on it.

**Comment by UdAyAn123** [comment]
Can I add some?

**Comment by Navi68** [comment]
can i some ?
