### ISSUE TITLE
Create a user profile with user's followed artists, albums, playlists, liked songs in Codepeak-Spotify branch

### ISSUE THREAD

**Issue by Abhijeet-2003** [flyingsonu122/tarana#130]

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 Please assign.

**Comment by Abhijeet-2003** [comment]
For this issue #130 , creating a user profile with artists, albums etc also requires fetching data from API.
Also, as there is no previous code for the user profile page, I’ll have to make the whole page from scratch.
So, could you please award 20 points for this.

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 please reply.

**Comment by flyingsonu122** [comment]
> @flyingsonu122 please reply.

okay go ahead @Abhijeet-2003

**Comment by Abhijeet-2003** [comment]
> > @flyingsonu122 please reply.
> 
> okay go ahead @Abhijeet-2003

Could you please change the label to 20 points then @flyingsonu122.

**Comment by flyingsonu122** [comment]
your PR will be given 20 points, no worries

**Comment by Abhijeet-2003** [comment]
I've sent a pr #134. Kindly review and merge. @flyingsonu122

**Comment by flyingsonu122** [comment]
Thanks merged it
