### ISSUE TITLE
Make "newmain" branch mobile responsive 

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#136]
Check newmain branch interface and make it responsive to mobile screen

**Comment by iconicsudip** [comment]
Hi @flyingsonu122 

I am a frontend developer, I have fixed the newmain branch mobile responsive problem. Assign me this task to show my changes in your code.

Then I can make PR.
Thanks,

**Comment by iconicsudip** [comment]
In which branch i will make PR ?

**Comment by iconicsudip** [comment]
I made a PR yesterday.please review

**Comment by flyingsonu122** [comment]
Pls share screenshots of new changes

**Comment by iconicsudip** [comment]
## Normal Screen
![image](https://user-images.githubusercontent.com/61116990/230611706-611318b4-38a1-4d9e-aefa-073c416d8489.png)

## Mobiles
![image](https://user-images.githubusercontent.com/61116990/230611886-f0201206-f618-4eb7-8749-d42b176f1944.png)


Tap on playlist to open and tap on playlist to close
![image](https://user-images.githubusercontent.com/61116990/230611977-818da614-0631-46fa-b6bf-f75db1f0abd1.png)

**Comment by flyingsonu122** [comment]
Pls make these share, playlist, theme and visit at bottom of the screen

**Comment by iconicsudip** [comment]
Sorry for late reply..
Okay

**Comment by iconicsudip** [comment]
Done
