### ISSUE TITLE
put tile display to the songs

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#14]

**Comment by itsmeAnubhab** [comment]
I am GSSOC'2 participant. I would like to work on this.

**Comment by itsmeAnubhab** [comment]
can you please elaborate?

**Comment by flyingsonu122** [comment]
> can you please elaborate?

@keerthinamballa please cooperate here

**Comment by keerthinamballa** [comment]
### Giving Grid Display to playlist section.

- All the playlists will be having grid display so the user can easily access any of them easily.
- Adding searching and sorting so that user can find the desired playlist easily.

**Comment by itsmeAnubhab** [comment]
something like this?
https://codepen.io/assimilate/pen/aVKpYp

**Comment by keerthinamballa** [comment]
@flyingsonu122  I am working on the issue I proposed. I would also update you with my result soon.

**Comment by flyingsonu122** [comment]
> @flyingsonu122 I am working on the issue I proposed. I would also update you with my result soon.

looking forward for your update
