### ISSUE TITLE
Code Optimization and File Ordering

### ISSUE THREAD

**Issue by Kumar-laxmi** [flyingsonu122/tarana#15]
In the Project I found all CSS files and JS files clubbed together.

So they can be organised in directory to increase readability of reduce complexity.

Also it found two JS function code getting repeated, so we can organise them in single JS file and just call them instead of writing those code again.

**Comment by flyingsonu122** [comment]
@Kumar-laxmi nice suggestions, assigning to you.

**Comment by flyingsonu122** [comment]
can you please do it again after new changes

**Comment by Kumar-laxmi** [comment]
ya sure I will try

**Comment by Kumar-laxmi** [comment]
Bro please close this

**Comment by flyingsonu122** [comment]
> Bro please close this

Add proper links to index.html

**Comment by Kumar-laxmi** [comment]
ok
