### ISSUE TITLE
Design this full website's UI in Figma

### ISSUE THREAD

**Issue by eshan1925** [flyingsonu122/tarana#20]
Hey, I am **Eshan Gupta** the project Mentor for this project. 

- You need to design the Ui of this website in Figma, don't do a lot of changes but make it look attractive.
- Share with us the link of the Figma (View-Only Acess) through making a pull request and attaching the link in the ReadMe.
- The best and the first UI we get in the coming week will be given as a Level-3 contribution.
- You can do this issue(task) with a maximum of 3 people. Obviously, the issue will be assigned to any one of the people but the points will be given to all 3 of you.
- Happy Contributing ❤️

**please do this before 8th of March**

**Comment by flyingsonu122** [comment]
Welcome @eshan1925 
Thanks for this suggestions

**Comment by Prajnaprabhu3** [comment]
I would be willing to join in contributing as well

**Comment by ZZENGAA** [comment]
hello ,i am ajitesh soni
I was looking exactly something like that to contribute so i also wanna contribute!!

**Comment by eshan1925** [comment]
Hey @ZZENGAA, @Prajnaprabhu3, and @M-anisha-coder you all 3 can collaborate with each other and bring us a design by the 8th of March.
As if you all 3 will work independently then any 2 of you may have to discard their design at the end.
So my recommendation would be to distribute your work and make us a design.

Anyways the last decision is in your hands. You can contact each other through discord or mail or LinkedIn.

Happy Contributing🙌

**Comment by M-anisha-coder** [comment]
I am ready to work together . If @ZZENGAA and @Prajnaprabhu3 are okay with this.
Let me know by morning.

**Comment by Prajnaprabhu3** [comment]
yes, works for me

**Comment by M-anisha-coder** [comment]
Join this telegram group we will work together @Prajnaprabhu3 
https://t.me/Learningopportunities

**Comment by ZZENGAA** [comment]
i am also ready to work with both of you!! sorry for the late reply guys!!

**Comment by ZZENGAA** [comment]
can you guys provides your discord ids?
mine is _AJ_#9335

**Comment by ZZENGAA** [comment]
@M-anisha-coder @Prajnaprabhu3 ?

**Comment by Prajnaprabhu3** [comment]
Prajna#6097  -> discord id

**Comment by M-anisha-coder** [comment]
manisha visvkrama#8457

**Comment by BeginnerCoder21** [comment]
Can I work on this issue? @flyingsonu122

**Comment by A9Aru** [comment]
Can I work on this issue? @flyingsonu122

**Comment by BeginnerCoder21** [comment]
@flyingsonu122 Okay, Thanks!!

**Comment by A9Aru** [comment]
Thanks @flyingsonu122!

**Comment by parths9** [comment]
hi @flyingsonu122, could I work on this issue

**Comment by parths9** [comment]
thank you @flyingsonu122

**Comment by flyingsonu122** [comment]
@Prajnaprabhu3 @M-anisha-coder @Prajnaprabhu3 
share link of design
allow permissions so that we can see it. [flyingsonu736@gmail.com](mailto:flyingsonu736@gmail.com)

**Comment by Prajnaprabhu3** [comment]
@flyingsonu122 should I make a new PR

**Comment by flyingsonu122** [comment]
@Prajnaprabhu3 it looks nice ,

-  can you also make for mobile devices
-  share public so everyone can see

**Comment by BeginnerCoder21** [comment]
@flyingsonu122 I and @parths9 has also created the UI, I have shared the Figma file with you, please check!!

**Comment by flyingsonu122** [comment]
> @flyingsonu122 I and @parths9 has also created the UI, I have shared the Figma file with you, please check!!

It's awesome

**Comment by flyingsonu122** [comment]
We all should discuss what to do next.

@eshan1925 please arrange a meeting for all participants to the project

**Comment by flyingsonu122** [comment]
We have got 2 awesome design, on specified time.

I am very thankful to you all.

Congratulations 🎉

**Comment by parths9** [comment]
Thank you @flyingsonu122 😊

**Comment by smrithi1912** [comment]
@eshan1925 hi, are you still accepting designs?

**Comment by flyingsonu122** [comment]
> @eshan1925 hi, are you still accepting designs?

yes
