### ISSUE TITLE
docs: Add PR Template

### ISSUE THREAD

**Issue by Pradumnasaraf** [flyingsonu122/tarana#21]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 22-50-29](https://user-images.githubusercontent.com/51878265/156217377-37df2ff3-28cb-4209-8083-cce61b4be227.png)

**Comment by Pradumnasaraf** [comment]
Hey! @flyingsonu122, please check this issue,
Thank you

**Comment by flyingsonu122** [comment]
@eshan1925 do we need this

**Comment by eshan1925** [comment]
> @eshan1925 do we need this

We can do this...
But I don't have much idea on how to set this up, assign someone who can establish the workflow correctly.

**Comment by Pradumnasaraf** [comment]
> > @eshan1925 do we need this
> 
> We can do this... But I don't have much idea on how to set this up, assign someone who can establish the workflow correctly.

Hey @eshan1925 there is no workflow required, it's a normal template (No GitHub actions), like [this](https://github.com/Pradumnasaraf/Pradumnasaraf/issues/new/choose)

**Comment by Pradumnasaraf** [comment]
> > > @eshan1925 do we need this
> > 
> > 
> > We can do this... But I don't have much idea on how to set this up, assign someone who can establish the workflow correctly.
> 
> Hey @eshan1925 there is no workflow required, it's a normal template (No GitHub actions), like [this](https://github.com/Pradumnasaraf/Pradumnasaraf/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
> 
> Here are official docs too - [Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

Should I also make a PR for this?

**Comment by Pradumnasaraf** [comment]
> > > @eshan1925 do we need this
> > 
> > 
> > We can do this... But I don't have much idea on how to set this up, assign someone who can establish the workflow correctly.
> 
> Hey @eshan1925 there is no workflow required, it's a normal template (No GitHub actions), like [this](https://github.com/Pradumnasaraf/Pradumnasaraf/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
> 
> Here are official docs too - [Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

@eshan1925 Should I also make a PR for this?
