### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by Pradumnasaraf** [flyingsonu122/tarana#22]
### Chnages 
- Adding Issue templates
- Template path **`.github/ISSUE_TEMPLATE`**

### Template Types
![Screenshot from 2022-03-01 21-03-49](https://user-images.githubusercontent.com/51878265/156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0.png)

### Template Preview (while creating an issue - bug.)
![Screenshot from 2022-03-01 18-03-48](https://user-images.githubusercontent.com/51878265/156169861-53b91128-a1aa-4751-805e-affb8a4924a3.png)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 22-50-29](https://user-images.githubusercontent.com/51878265/156217510-5f8b1636-9cdf-4931-b899-b80c6512c9e5.png)

- Contribution towards GSsoc`22, Thank you

**Comment by Pradumnasaraf** [comment]
Hey! @flyingsonu122, please check this issue

**Comment by flyingsonu122** [comment]
@eshan1925 do we need this

**Comment by eshan1925** [comment]
> @eshan1925 do we need this

We can do this...
But I don't have much idea on how to set this up, assign someone who can establish the workflow correctly.

**Comment by Pradumnasaraf** [comment]
> > @eshan1925 do we need this
> 
> We can do this... But I don't have much idea on how to set this up, assign someone who can establish the workflow correctly.

Hey @eshan1925 there is no workflow required, it's a normal template (No GitHub actions), like [this](https://github.com/Pradumnasaraf/Pradumnasaraf/issues/new/choose)

**Comment by eshan1925** [comment]
Alright, @Pradumnasaraf How can we use it each time a user creates a new issue or PR.
For example, if there is new PR.

Then we want the user to have some text from before in the description.
Like what is that you are changing etc.
Please explain as I have never used this feature before.

**Comment by Pradumnasaraf** [comment]
> Alright, @Pradumnasaraf How can we use it each time a user creates a new issue or PR. For example, if there is new PR.
> 
> Then we want the user to have some text from before in the description. Like what is that you are changing etc. Please explain as I have never used this feature before.

@eshan1925  It helps us in structuring the Issue info in proper format and also when you open a specific issue it will auto add a label to it so that you don't have to manually put it or Add no need to add special GitHub actions. Also, it will help you when you are releasing the packages in future

Here are the official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by Pradumnasaraf** [comment]
For the test, you can try opening one issue here [https://github.com/Pradumnasaraf/Pradumnasaraf.github.io/issues/new/choose] :)

**Comment by eshan1925** [comment]
> > Alright, @Pradumnasaraf How can we use it each time a user creates a new issue or PR. For example, if there is new PR.
> > Then we want the user to have some text from before in the description. Like what is that you are changing etc. Please explain as I have never used this feature before.
> 
> @eshan1925 It helps us in structuring the Issue info in proper format and also when you open a specific issue it will auto add a label to it so that you don't have to manually put it or Add no need to add special GitHub actions. Also, it will help you when you are releasing the packages in future
> 
> Here are the official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Ok, Thanks a lot as I can see in the docs we need some templating and that template is a file.
So can you make a PR and reference the issue?

**Comment by Pradumnasaraf** [comment]
> > > Alright, @Pradumnasaraf How can we use it each time a user creates a new issue or PR. For example, if there is new PR.
> > > Then we want the user to have some text from before in the description. Like what is that you are changing etc. Please explain as I have never used this feature before.
> > 
> > 
> > @eshan1925 It helps us in structuring the Issue info in proper format and also when you open a specific issue it will auto add a label to it so that you don't have to manually put it or Add no need to add special GitHub actions. Also, it will help you when you are releasing the packages in future
> > Here are the official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
> 
> Ok, Thanks a lot as I can see in the docs we need some templating and that template is a file. So can you make a PR and reference the issue?

Didn't get that should I work on this issue #22?

**Comment by eshan1925** [comment]
> > > > Alright, @Pradumnasaraf How can we use it each time a user creates a new issue or PR. For example, if there is new PR.
> > > > Then we want the user to have some text from before in the description. Like what is that you are changing etc. Please explain as I have never used this feature before.
> > > 
> > > 
> > > @eshan1925 It helps us in structuring the Issue info in proper format and also when you open a specific issue it will auto add a label to it so that you don't have to manually put it or Add no need to add special GitHub actions. Also, it will help you when you are releasing the packages in future
> > > Here are the official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
> > 
> > 
> > Ok, Thanks a lot as I can see in the docs we need some templating and that template is a file. So can you make a PR and reference the issue?
> 
> Didn't get that should I start working on issue #22?

Yess
