### ISSUE TITLE
Add share button

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#23]
- share particular song link so that someone play that particular song after visiting website by clicking shared link
- features to share on all social media platforms
- copy to clipboard features

**Comment by zugzwang03** [comment]
I would like to work on this issue under GSSoC22.

**Comment by zugzwang03** [comment]
Also, can you please inform the time limit within which I have to complete it as the difficulty label is not mentioned here.

**Comment by flyingsonu122** [comment]
> Also, can you please inform the time limit within which I have to complete it as the difficulty label is not mentioned here.

Time limit:  within 6 days

**Comment by flyingsonu122** [comment]
@sulogna2001 are you working on it.
you & @zugzwang03 can work together

**Comment by flyingsonu122** [comment]
who is working on it, **first person to complete** will be considered

**Comment by mayank-del** [comment]
@flyingsonu122   Is this issue is still on??

**Comment by mayank-del** [comment]
@flyingsonu122  , can i work under this issue under gssoc22

**Comment by flyingsonu122** [comment]
already implemented in **develop** branch, you modify it

**Comment by flyingsonu122** [comment]
Done
