### ISSUE TITLE
Enhancement : SEARCH button on the navbar

### ISSUE THREAD

**Issue by shivam123-dev** [flyingsonu122/tarana#30]
**Description**

 - I want to replace the SEARCH button on the navbar with search svg icon
 - This will Improve your website’s User Interface(UI).

**Screenshot**
   
**Replaced the SEARCH button with its SVG icon**
![image](https://user-images.githubusercontent.com/81038095/156870075-cea8a073-e38b-4700-9e91-b3e8540b958a.png)

 - Please assign me on this issue under GSSOC '22 @flyingsonu122

**Comment by flyingsonu122** [comment]
This is the actual website https://www.sonu.live/tarana
