### ISSUE TITLE
Code readability

### ISSUE THREAD

**Issue by Kushal-2002** [flyingsonu122/tarana#31]
While working on one of the features I have found that the code is not well-structured and are not readable. I want to add comments in the code files and also arrange the files in proper order so that it becomes easier for others to read and understand the code and also contribute in the project.

**Comment by Kushal-2002** [comment]
I have got files ready, I will make the PR as soon as I am assigned.

**Comment by flyingsonu122** [comment]
go ahead @Kushal-2002
