### ISSUE TITLE
[UI Improvement]

### ISSUE THREAD

**Issue by agcodester** [flyingsonu122/tarana#32]
Hi @flyingsonu122 this is Aum here. 
I would like to work on improving the UI of your Tarana Music Player.
My suggestions include displaying the list of songs along with their relevant pictures on the left and the current playing music with its pictures and media controls on the right.
I also wish to add a sticky navbar and display it using the CSS "z-index property".
Hope, you will like my suggestions. Expect to hear back from you and get assigned on the same.

**Comment by flyingsonu122** [comment]
do it @agcodester

**Comment by roy-shivam** [comment]
hello @flyingsonu122  sir I want to add animated background if the music player, by which it looks more attractive
please assign me this task.

**Comment by flyingsonu122** [comment]
@agcodester @roy-shivam 
solve this #44
