### ISSUE TITLE
Change the Hovering effect of the Buttons

### ISSUE THREAD

**Issue by Yasshu55** [flyingsonu122/tarana#40]
I have found a bug in the website. Share button doesn't have a Hover Effect like POST A COMMENT, READ MORE button.
I would like to change the Hover Effect for the buttons, which Transits from Left to right and add a Hover Effect to the Share Button

**Comment by mayank-del** [comment]
Can i work under this issue under gssoc22

**Comment by flyingsonu122** [comment]
Do it

**Comment by mayank-del** [comment]
@flyingsonu122 , i am not getting any share button on your project, can you tell me exact path?

**Comment by flyingsonu122** [comment]
check **develop** branch
