### ISSUE TITLE
Make it responsive 

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#41]
Make website response to every screen sizes

**Comment by Apexshya** [comment]
I am GSSoC'22 contributor and I would like to work on this issue.

**Comment by randomuy1289** [comment]
I am a GSSoc'22 contributor and I would like to work on this issue.

**Comment by mohitahlawat2001** [comment]
i want to contribute can you assign me

**Comment by flyingsonu122** [comment]
> @flyingsonu122 , can i work under this issue under gssoc22

yes, you can

**Comment by mayank-del** [comment]
@flyingsonu122  please merge it, i made it responsive upto 300 px and below also

**Comment by navyasharma0203** [comment]
Is it done..or Can I work on this??

**Comment by flyingsonu122** [comment]
> Is it done..or Can I work on this??

You should work on this

**Comment by navyasharma0203** [comment]
Please check....problem resolved for all the pages...signup page wasn't responsive...that too resolved :)

**Comment by flyingsonu122** [comment]
> Please check....problem resolved for all the pages...signup page wasn't responsive...that too resolved :)

create pull request @navyasharma0203

**Comment by navyasharma0203** [comment]
> > Please check....problem resolved for all the pages...signup page wasn't responsive...that too resolved :)
> 
> create pull request @navyasharma0203

There are pretty one line minute addons only to the code....please review it...I don't think a pr is needed as such...

**Comment by flyingsonu122** [comment]
> 

where is it to review?
