### ISSUE TITLE
Improve about us section

### ISSUE THREAD

**Issue by aashi2912** [flyingsonu122/tarana#55]
I want to contribute to this project under GSSOC'22. I want to improve the Style/design/ CSS of the about us page and make it more attractive and organized.

![image](https://user-images.githubusercontent.com/52272710/159270477-c066c317-d7c0-4128-aa12-3d76a1eb9b57.png)

@flyingsonu122

**Comment by aashi2912** [comment]
Hi, I am trying to push the changes before creating a PR. but it gives below error. Can u please see?

![image](https://user-images.githubusercontent.com/52272710/159442429-3339d46e-e2f2-4faf-8df3-98a1ec05c885.png)

@flyingsonu122

**Comment by flyingsonu122** [comment]
are you logged in to git?

**Comment by aashi2912** [comment]
yes

**Comment by flyingsonu122** [comment]
you can update files on github itself

**Comment by aashi2912** [comment]
okk..the issue got resolved. Thanks
