### ISSUE TITLE
Adding search logo for search songs functionality.

### ISSUE THREAD

**Issue by ankeeta-ahire** [flyingsonu122/tarana#59]
This would enhance the user experience. Please assign me this issue.

**Comment by Rishita489** [comment]
Hey @flyingsonu122  , I am a GSSOC'22 contributor . Can you please assign this issue to me . I have send the PR solving this issue . Can you please review and merge it .

**Comment by Rishita489** [comment]
Hey @flyingsonu122 , I have made a new pull request in develop branch . Please assign this issue to me and review and merge my PR.
