### ISSUE TITLE
[FEATURE] I Will Add Email Password Authentication

### ISSUE THREAD

**Issue by Abh1shekSingh** [flyingsonu122/tarana#69]
### Description

I will add email Password Authentication

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Please assign the task.

**Comment by flyingsonu122** [comment]
do your work, everything will be taken care off

**Comment by Abh1shekSingh** [comment]
@flyingsonu122  I am done with adding the Email Auth functionality, and is working the exact way it should work. But due to some reason I again forked and clone your repo, and now i cant see home page where songs play will appear.

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 please check discord DM. I have some queries and doubts. It would be Hard to all here. So I have DMd you on discord
