### ISSUE TITLE
suggest new features

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#7]
**suggest new features for the music player**

- [ ]  suggest new features by creating new issues

**note**: all are welcome, no need to take permission

**Comment by sanket95droid** [comment]
1.) Like 🤍 feature for songs, because playlist only reveals the user's style.
2.) Lyrics for people to understand the song.
Also if I was to work on it I would've definitely changed the styling CSS.
😄

**Comment by flyingsonu122** [comment]
@sanket95droid go ahead and make a better design

**Comment by sanket95droid** [comment]
I can only make the PR after 1 March after particular mentors get assigned to the project also then my PR will be considered.

**Comment by flyingsonu122** [comment]
You can start working on the project from today, PR can be raised from 1st of march.

**Comment by Kanika1309** [comment]
Hi...I am GSSoC'22 participant. I want to work on backend using nodeJS and mongodb to add features like - 
1. search a song
2. creating your own playlist by artist or genre 
Let me know if there is any tasks that can be assigned to me.

**Comment by flyingsonu122** [comment]
> Hi...I am GSSoC'22 participant. I want to work on backend using nodeJS and mongodb to add features like -
> 
> 1. search a song
> 2. creating your own playlist by artist or genre
>    Let me know if there is any tasks that can be assigned to me.

Hello @Kanika1309 I am assigning you #11

**Comment by keerthinamballa** [comment]
Hello, I am GSSoC'22 contributor. I would like to put tile display to the song .

**Comment by Shama-Devi-93** [comment]
Hello, I am GSSoc'22 contributor. I would like to work on the issue to display lyrics.

**Comment by amanagnihotri1** [comment]
Hii,I'm a GSSoc'22 participant and i want to contribute in this project.
Feature That i want to add are
1.Adding Tag to a Song to make it more easy for user to listen to particular mood music only.
2. Making Search Functioning more easy for user by adding debouncing function 
At Last if any one person want to join / contribute with me feel free to contact me on GSSoc'22 discord server as Aman Agnihotri | Contributor

**Comment by neeraj542** [comment]
can I work on this issue

**Comment by flyingsonu122** [comment]
> can I work on this issue

yes pls

**Comment by neeraj542** [comment]
please assign me

**Comment by flyingsonu122** [comment]
> please assign me

if have any suggestions, create a new issue, I will assign that to you

**Comment by neeraj542** [comment]
okay

**Comment by neeraj542** [comment]
I can only suggest you about new feaures like what you can addup and also can tell you about what should remove from this
