### ISSUE TITLE
[FEATURE] I WILL ADD MOBILE AND OTP AUTHENTICATION

### ISSUE THREAD

**Issue by Abh1shekSingh** [flyingsonu122/tarana#74]
### Description

MOBILE AND OTP AUTH

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Can I get Assign to this also

**Comment by flyingsonu122** [comment]
resolve these first @Abh1shekSingh 

![image](https://user-images.githubusercontent.com/51280276/167094885-c40d612e-d7a8-465b-9845-ee7ab156fefe.png)

![image](https://user-images.githubusercontent.com/51280276/167095263-bcbed537-3b5e-445d-aafa-57a72fc21225.png)


![image](https://user-images.githubusercontent.com/51280276/167095311-6a84574a-4766-4bba-9477-c573bd8e5e0a.png)

**Comment by Abh1shekSingh** [comment]
Sure

**Comment by flyingsonu122** [comment]
do this @Abh1shekSingh

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Can you please help me out with an issue. actually mobile OTP auth form is not working . I hav esetup the whole code. but it is not working

**Comment by flyingsonu122** [comment]
@eshan1925 please help here
