### ISSUE TITLE
Resolve The Breaking Code

### ISSUE THREAD

**Issue by Abh1shekSingh** [flyingsonu122/tarana#75]
@flyingsonu122  Assign Please, I will Resolve it

**Comment by flyingsonu122** [comment]
signin up is not working fine, check here https://flyingsonu122.github.io/tarana


also, show meggage for error, and show signed in email

**Comment by Abh1shekSingh** [comment]
![Uploading 16518263855801105433245317075278.jpg…]()
You are getting authenticated @flyingsonu122

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 to me everything is working very fine

**Comment by Abh1shekSingh** [comment]
Also you are also get authenticated with a@gmail.com

**Comment by flyingsonu122** [comment]
check how your have to do https://sonukushwaha.me/ggps/public/signin.html

**Comment by Abh1shekSingh** [comment]
dont worry @flyingsonu122 First I will work on backend then setup cool front end too

**Comment by flyingsonu122** [comment]
okay

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Please Give the Labels and marks for this PR sir.
