### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by ericdrosado** [flyingsonu122/tarana#83]
`Learn` repos should have a LEARN.md file to teach another student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn. 

If you feel your project is too large to teach step by step how to build it, consider just teaching a certain tool or implementation that your project utilizes.

**Comment by Abhijeet-2003** [comment]
Can I work on this and make a LEARN.md for Codepeak-Spotify Branch ? @flyingsonu122

**Comment by flyingsonu122** [comment]
> Can I work on this and make a LEARN.md for Codepeak-Spotify Branch ? @flyingsonu122

Yes please

**Comment by flyingsonu122** [comment]
@Abhijeet-2003 pls work on this

**Comment by Abhijeet-2003** [comment]
Yeah sure. @flyingsonu122.

**Comment by Abhijeet-2003** [comment]
I've sent a pr @flyingsonu122. Please review and merge. Kindly award points for the previous 2 PRs #128, #131  
and for raising 2 issues #129, #130  as well.
