### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericdrosado** [flyingsonu122/tarana#85]
A README is often the first item a visitor will see when visiting your repository. We recommend that your README includes information on:
* What the project does
* Why the project is useful
* How users can get started with the project
* Explain to users that there is a LEARN.md
* Who maintains and contributes to the project

**Comment by SxxAq** [comment]
I want to work on this issue please Assign it to me

**Comment by flyingsonu122** [comment]
> I want to work on this issue please Assign it to me

@SxxAq pls work on it, consider these points

![image](https://user-images.githubusercontent.com/51280276/208239052-69a14b23-f0a3-421d-9353-319720b9ae63.png)

**Comment by SxxAq** [comment]
please Assign to someone else

**Comment by SattyamSamania** [comment]
@flyingsonu122 if the issue is still open can I work on this?

**Comment by flyingsonu122** [comment]
> @flyingsonu122 if the issue is still open can I work on this?

Yes please

**Comment by flyingsonu122** [comment]
> @flyingsonu122 if the issue is still open can I work on this?

Yes please

**Comment by flyingsonu122** [comment]
@SattyamSamania any update
