### ISSUE TITLE
Want To make LOGO for this project 

### ISSUE THREAD

**Issue by nik132-eng** [flyingsonu122/tarana#87]
this project has a basic music logo want to change with the TARANA name in it. can you please assign me this work so I can contribute To GSSOC? 

thank you

**Comment by flyingsonu122** [comment]
please make it @nik132-eng

**Comment by nik132-eng** [comment]
here are some suggestions

**Comment by nik132-eng** [comment]
can you please refer to it and let me know which one you like and if you don't like it we can do further study and make logo. 
@flyingsonu122

**Comment by flyingsonu122** [comment]
@Nihal-Priyadarshi @SinhaAnishKumar @Abh1shekSingh which one is suitable

**Comment by nik132-eng** [comment]
I can provide these logos in png, Jpg, SVG format.

thank you.

**Comment by nik132-eng** [comment]
@flyingsonu122  please check my logos and select one of them. and If any changes are required let me know.

waiting for your reply thank you.

**Comment by flyingsonu122** [comment]
> @flyingsonu122 please check my logos and select one of them. and If any changes are required let me know.
> 
> waiting for your reply thank you.

![image](https://user-images.githubusercontent.com/51280276/169820882-2f1c192c-d760-4883-99f8-9561ca360cde.png)


This one can be improved, it's good

**Comment by Nihal-Priyadarshi** [comment]
> @Nihal-Priyadarshi @SinhaAnishKumar @Abh1shekSingh which one is suitable

Fourth is better from all but can be improved.
