### ISSUE TITLE
add sign up and login features

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#9]
1. login with social media account
2. login with email & password
3. login with mobile and OTP
4. login with a magic link on email

**Comment by Navi68** [comment]
sir, can you assign me this issue for gssoc 22.

**Comment by flyingsonu122** [comment]
@Navi68 assigned to you, start contributing now

**Comment by Navi68** [comment]
Ok sir thank you👐

**Comment by Navi68** [comment]
Hello sir currently you have assign me login page. I am good in frontend
part, i just google it and found out magic link generation is all about
backend part i am not so goid in backend. What i do know should i work on
just frontend part? Please help me.

**Comment by flyingsonu122** [comment]
Do whatever possible

**Comment by Anish1411** [comment]
hii.. , i want to work on this issue , assign it to me under gssoc'22.

**Comment by flyingsonu122** [comment]
Go ahead @Anish1411

**Comment by Anish1411** [comment]
okk thankx

**Comment by Abh1shekSingh** [comment]
HI @flyingsonu122 Please assign this issue to me. I would love working on it

**Comment by yogitasaini** [comment]
Please assign this task to me

**Comment by Aditya3403** [comment]
I would like to work on this issue .Kindly assign it to me.

**Comment by lokita282** [comment]
I would like to work on this issue under GSSOC '22

**Comment by amanagnihotri1** [comment]
i would like to contribute on this feature, if u allow me 
i can work upon social media account login 
i am open to work with one more person if anyone open for this please contact on GSSoc's Discord Server.

**Comment by flyingsonu122** [comment]
has anyone done it, please ping me

**Comment by roy-shivam** [comment]
sir can you assign me this under GSSOC 2022,

**Comment by ayush25102001** [comment]
Can I create the schema for the userModel with fields like name email and password.
When the user signs up the credentials will be added to the database(MongoDB) and then will be checked when he logs in.
I wish to work on backend part.

**Comment by ayush25102001** [comment]
Can I create frontend React login and SignUp components, I will provide a button in the Header of the Homepage.

Participant under gssoc'22

**Comment by flyingsonu122** [comment]
@ayush25102001 do it.

> Can I create frontend React login and SignUp components, I will provide a button in the Header of the Homepage.
> 
> Participant under gssoc'22

Please Do it

**Comment by ayush25102001** [comment]
Can I set up authentication using JWT at the backend here if the user logs in to our application we provide a user with a token and the, later user would be required to have that token to access the protected routes of the application.
Wishing to work on the backend part of the issue.
Participant under Gssoc’22

**Comment by flyingsonu122** [comment]
> 

@ayush25102001 are you working on it?

**Comment by flyingsonu122** [comment]
anyone completed it?

**Comment by ayush25102001** [comment]
> @ayush25102001 are you working on it?

U did not assign it to me sir.

**Comment by Abh1shekSingh** [comment]
@flyingsonu122  please assign it to me. I will do it quickly

**Comment by flyingsonu122** [comment]
> @flyingsonu122 please assign it to me. I will do it quickly

alright,  do it 👍 
@Abh1shekSingh

**Comment by Abh1shekSingh** [comment]
> > @flyingsonu122 please assign it to me. I will do it quickly
> 
> alright, do it 👍 @Abh1shekSingh

Do you want me to first pop up signin page and then let viewer see ur content. Or I just add a Page, and it's user wish to signin or not?

**Comment by flyingsonu122** [comment]
> I just add a Page, and it's user wish whether to signin or not?

just add a Page, and it's user wish whether to signin or not?

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Bhai pehle toh mereko website smjhao, kuch smjh hi nhi aa raha, itna hochj poch kr rkha hai sb kuch, pata hi nhi lg raha, header kaha pe hai, button add kaise kru mein ?

**Comment by flyingsonu122** [comment]
> @flyingsonu122 Bhai pehle toh mereko website smjhao, kuch smjh hi nhi aa raha, itna hochj poch kr rkha hai sb kuch, pata hi nhi lg raha, header kaha pe hai, button add kaise kru mein ?

If you can't figure it out, just leave it

**Comment by Abh1shekSingh** [comment]
I fugured out, some how 

> > @flyingsonu122 Bhai pehle toh mereko website smjhao, kuch smjh hi nhi aa raha, itna hochj poch kr rkha hai sb kuch, pata hi nhi lg raha, header kaha pe hai, button add kaise kru mein ?
> 
> If you can't figure it out, just leave it, But can you please check the DM on discord, I have mentioned some request over there

**Comment by amanagnihotri1** [comment]
Hey @Abh1shekSingh  can i work on this issue with you ?please reply

**Comment by Abh1shekSingh** [comment]
@amanagnihotri1  I am sorry, i have completed this part.

**Comment by flyingsonu122** [comment]
@amanagnihotri1 you can work on this #44

**Comment by navyasharma0203** [comment]
Can I work on this??

**Comment by amanagnihotri1** [comment]
@navyasharma0203 im working on this but ask mentor if 2 people can work on this

**Comment by amanagnihotri1** [comment]
i can work on login with email and pasword and with magic link

**Comment by flyingsonu122** [comment]
> with magic link

do this

**Comment by amanagnihotri1** [comment]
okk

**Comment by flyingsonu122** [comment]
Done
