### ISSUE TITLE
make new interface

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#94]
1. **Make New Look Like This**
2. if possible,make mobile responsive (optional)
3. do not clone it, download only html css and js files only , add dummy img and songs on local machine, make changes, and upload your files
4. host forked repo and share link
5. make sure, it is fully working

![Desktop - 1](https://user-images.githubusercontent.com/51280276/158061509-a15f891a-a845-4dd1-9256-56a6dafe3a1b.png)

![Desktop - 2](https://user-images.githubusercontent.com/51280276/158061529-53e41ccf-7ab2-48b6-9c39-55ba8f2aa0bb.png)

![Desktop - 3](https://user-images.githubusercontent.com/51280276/158061542-f6a13a02-9610-4e5e-b1ce-b420c538c391.png)

**Comment by ozlemertosun** [comment]
Hi, I want to work on this :-)

**Comment by flyingsonu122** [comment]
> Hi, I want to work on this :-)

Yes pls, go ahead

**Comment by ozlemertosun** [comment]
@flyingsonu122 Do you have any files you can share with me, I need color codes :-)

**Comment by flyingsonu122** [comment]
Leave it, it's done
