### ISSUE TITLE
Login and sign up features 

### ISSUE THREAD

**Issue by flyingsonu122** [flyingsonu122/tarana#98]

**Comment by Shinchan3102** [comment]
Hey @flyingsonu122 can i you assign me the issue i want to work on it

**Comment by raunak-mishra** [comment]
@flyingsonu122  I'd like to take this up. Kindly assign it. Thanks

**Comment by flyingsonu122** [comment]
> Hey @flyingsonu122 can i you assign me the issue i want to work on it

@Shinchan3102 assigned to you
